### ISSUE TITLE
'Identifier "users" is not defined' error on local copy

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/pipo#12]
Authentication is not working locally. Runned composer, but maybe the sql needs an update?

**Comment by phpetra** [comment]
Ah no, you nee to add some passwords to your local parameters file.... I'll be emailing them. Hang on ....

**Comment by phpetra** [comment]
Voor in je parameters.php:

// BASIC USERS with PASSWORD
$app['users'] = array(
     'user' => 'password',
);

**Comment by mmmenno** [comment]
:-)
